map:
  notebooks:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: bccfcb6b1457b189c8ef483be884efa1a2b3100d
    src: manifests
    dest: workbenches/notebooks
    ref_type: branch
    branch: stable
  odh-kserve-controller:
    src: config
    dest: kserve
    git.url: https://github.com/opendatahub-io/kserve
    git.commit: 6e7919c9933c42847731ba52b9f3387e097b504d
  odh-kf-notebook-controller:
    src: components/notebook-controller/config
    dest: workbenches/kf-notebook-controller
    git.url: https://github.com/opendatahub-io/kubeflow
    git.commit: 59a52974dbadd09df9c274e858d5766d42f53d55
  odh-notebook-controller:
    src: components/odh-notebook-controller/config
    dest: workbenches/odh-notebook-controller
    git.url: https://github.com/opendatahub-io/kubeflow
    git.commit: 59a52974dbadd09df9c274e858d5766d42f53d55
  odh-kuberay-operator-controller:
    src: ray-operator/config
    dest: ray
    git.url: https://github.com/opendatahub-io/kuberay
    git.commit: f991c184e326bdfdce4c072604d08ccd1d69a37e
  odh-trustyai-service-operator:
    src: config
    dest: trustyai
    git.url: https://github.com/opendatahub-io/trustyai-service-operator
    git.commit: ce63b1d59f337579939d56c9a1ed205ae3c701f0
  odh-model-registry-operator:
    src: config
    dest: modelregistry
    git.url: https://github.com/opendatahub-io/model-registry-operator
    git.commit: cffe9a5805e1a937b1044a47abf5709b52f2db43
  odh-dashboard:
    src: manifests
    dest: dashboard
    git.url: https://github.com/opendatahub-io/odh-dashboard
    git.commit: 8e77c4f52de37f02215a25505a03abfe0febbf93
  odh-training-operator:
    src: manifests
    dest: trainingoperator
    git.url: https://github.com/opendatahub-io/training-operator
    git.commit: da2a67ce5520e44d1ca361b4366d697a0171b9fd
  odh-feast-operator:
    src: infra/feast-operator/config
    dest: feastoperator
    git.url: https://github.com/opendatahub-io/feast
    git.commit: 124117138b5685c0d9aff8fc0855ce522dd10b60
additional_meta:
  odh-data-science-pipelines-operator-controller:
    git.url: ''
    vcs-ref: 5ce2472ce0adb818c6f88228508a541717e32e0f
  odh-model-controller:
    git.url: ''
    vcs-ref: c0ad4f386ab2d33c213b7b3b81e293c593b7e03f
  odh-trustyai-service:
    git.url: ''
    vcs-ref: 6199ea9b05e1dcf837fdeeb84e59bfca6b8c1eb0
  odh-mlmd-grpc-server:
    git.url: ''
    vcs-ref: bb983150d1f0a0526e35b8366e03a850f6350b10
  odh-ml-pipelines-api-server-v2:
    git.url: ''
    vcs-ref: d5e0ae8ac806902faab07a8564054020a4c689d2
  odh-ml-pipelines-persistenceagent-v2:
    git.url: ''
    vcs-ref: d5e0ae8ac806902faab07a8564054020a4c689d2
  odh-ml-pipelines-scheduledworkflow-v2:
    git.url: ''
    vcs-ref: d5e0ae8ac806902faab07a8564054020a4c689d2
  odh-ml-pipelines-driver:
    git.url: ''
    vcs-ref: d5e0ae8ac806902faab07a8564054020a4c689d2
  odh-ml-pipelines-launcher:
    git.url: ''
    vcs-ref: d5e0ae8ac806902faab07a8564054020a4c689d2
  odh-data-science-pipelines-argo-argoexec:
    git.url: ''
    vcs-ref: 47b594a506937c9977f544f9430a5c3ae138c861
  odh-data-science-pipelines-argo-workflowcontroller:
    git.url: ''
    vcs-ref: 47b594a506937c9977f544f9430a5c3ae138c861
  odh-model-registry:
    git.url: ''
    vcs-ref: a8caf754497ce236e1f4976283cd2399d7e26d38
  odh-feature-server:
    git.url: ''
    vcs-ref: 124117138b5685c0d9aff8fc0855ce522dd10b60
  odh-llama-stack-k8s-operator:
    git.url: ''
    vcs-ref: 5ad598b5d7da67e72ad29ce4717eb360c386a60c
  odh-llm-d-inference-scheduler:
    git.url: ''
    vcs-ref: 134b26ba05276c1d56e72617f46aad37b21936e9
  odh-llm-d-routing-sidecar:
    git.url: ''
    vcs-ref: ab94456dc48ead90f997a8566e0570b5b4482730
  odh-kserve-agent:
    git.url: ''
    vcs-ref: 6e7919c9933c42847731ba52b9f3387e097b504d
  odh-kserve-router:
    git.url: ''
    vcs-ref: 6e7919c9933c42847731ba52b9f3387e097b504d
  odh-kserve-storage-initializer:
    git.url: ''
    vcs-ref: 6e7919c9933c42847731ba52b9f3387e097b504d
  odh-ta-lmes-driver:
    git.url: ''
    vcs-ref: b07b6766890d675d8242b601cb5417b7cc3a6aac
  odh-ta-lmes-job:
    git.url: ''
    vcs-ref: d6c447a9f21fb7234f281397587690ebef46e664
  odh-fms-guardrails-orchestrator:
    git.url: ''
    vcs-ref: 4dfbbbc6a02b7456f254a59890ffe59c22aa2b55
  odh-trustyai-vllm-orchestrator-gateway:
    git.url: ''
    vcs-ref: 6494163b9a0b417bfa7964002bd2e0572147d5f5
  odh-built-in-detector:
    git.url: ''
    vcs-ref: 28dcc522f9ed3e1c8c45f4902f8eafee2ecf7b0b
  odh-pipeline-runtime-datascience-cpu-py312:
    git.url: ''
    vcs-ref: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-pipeline-runtime-minimal-cpu-py312:
    git.url: ''
    vcs-ref: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-pipeline-runtime-pytorch-cuda-py312:
    git.url: ''
    vcs-ref: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-pipeline-runtime-pytorch-rocm-py312:
    git.url: ''
    vcs-ref: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-pipeline-runtime-tensorflow-cuda-py312:
    git.url: ''
    vcs-ref: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-pipeline-runtime-tensorflow-rocm-py312:
    git.url: ''
    vcs-ref: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-workbench-codeserver-datascience-cpu-py312:
    git.url: ''
    vcs-ref: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-workbench-jupyter-datascience-cpu-py312:
    git.url: ''
    vcs-ref: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-workbench-jupyter-minimal-cpu-py312:
    git.url: ''
    vcs-ref: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-workbench-jupyter-minimal-cuda-py312:
    git.url: ''
    vcs-ref: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-workbench-jupyter-minimal-rocm-py312:
    git.url: ''
    vcs-ref: 6e3e9fb8bfe87057ffcc9c332d9175a3ee0c3987
  odh-workbench-jupyter-pytorch-cuda-py312:
    git.url: ''
    vcs-ref: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-workbench-jupyter-pytorch-rocm-py312:
    git.url: ''
    vcs-ref: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-workbench-jupyter-tensorflow-cuda-py312:
    git.url: ''
    vcs-ref: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-workbench-jupyter-tensorflow-rocm-py312:
    git.url: ''
    vcs-ref: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-workbench-jupyter-trustyai-cpu-py312:
    git.url: ''
    vcs-ref: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-guardrails-detector-huggingface-runtime:
    git.url: ''
    vcs-ref: 28dcc522f9ed3e1c8c45f4902f8eafee2ecf7b0b
  odh-model-registry-job-async-upload:
    git.url: ''
    vcs-ref: a8caf754497ce236e1f4976283cd2399d7e26d38
  odh-llama-stack-core:
    git.url: ''
    vcs-ref: 2cbd781ea0404730022d57b3345c4c8d4d0a61af
  odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312:
    git.url: ''
    vcs-ref: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312:
    git.url: ''
    vcs-ref: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-model-metadata-collection:
    git.url: ''
    vcs-ref: 2e4c260258c4e23fdc7f9e83e4bc740f5ae8b7be
  odh-mod-arch-gen-ai:
    git.url: ''
    vcs-ref: 8e77c4f52de37f02215a25505a03abfe0febbf93
  odh-kube-auth-proxy:
    git.url: ''
    vcs-ref: 558ba9d2294cb73415bc16baa81254843bc2f091
  odh-maas-api:
    git.url: ''
    vcs-ref: 53ecf9eaa0d24f084ee8b3f91798799a4edab6c0
  odh-trustyai-ragas-lls-provider-dsp:
    git.url: ''
    vcs-ref: fb6fe77e92e85ce96bf19e0becc53eb0bfc22ea4
  odh-training-cuda121-torch24-py311:
    git.url: ''
    vcs-ref: 7e1c2d0117261292d036f014dd09a0e3074ed1fd
  odh-training-cuda124-torch25-py311:
    git.url: ''
    vcs-ref: 070ba881a7d5927d5bd6f4cd9650088138a90400
  odh-training-cuda128-torch28-py312:
    git.url: ''
    vcs-ref: ea718d1d42cb489eebbba9d7d67da76345cac37d
  odh-training-rocm62-torch24-py311:
    git.url: ''
    vcs-ref: 8d62c5933f22005614c9e565ad18df890fa24d12
  odh-training-rocm62-torch25-py311:
    git.url: ''
    vcs-ref: 1c6062e5482eb55673524975756cf209d48bbfcb
  odh-training-rocm64-torch28-py312:
    git.url: ''
    vcs-ref: 61e655ba9363820d5fab9b568ef7921f55d003a9
  odh-mod-arch-model-registry:
    git.url: ''
    vcs-ref: 8e77c4f52de37f02215a25505a03abfe0febbf93
  odh-trainer:
    git.url: ''
    vcs-ref: 30bdcb8b0900e17e71793a0ef67bb950498dd462
