map:
  notebooks:
    src: manifests
    dest: workbenches/notebooks
    git.url: https://github.com/opendatahub-io/notebooks
    ref_type: branch
    branch: stable
    git.commit: bccfcb6b1457b189c8ef483be884efa1a2b3100d
  odh-kserve-controller:
    src: config
    dest: kserve
    git.url: https://github.com/opendatahub-io/kserve
    ref_type: branch
    branch: master
    git.commit: d48140434a6cba5e5df6da4a95c2c04b5c15e1dd
  odh-kf-notebook-controller:
    src: components/notebook-controller/config
    dest: workbenches/kf-notebook-controller
    git.url: https://github.com/opendatahub-io/kubeflow
    git.commit: 59a52974dbadd09df9c274e858d5766d42f53d55
  odh-notebook-controller:
    src: components/odh-notebook-controller/config
    dest: workbenches/odh-notebook-controller
    git.url: https://github.com/opendatahub-io/kubeflow
    git.commit: 59a52974dbadd09df9c274e858d5766d42f53d55
  odh-data-science-pipelines-operator-controller:
    src: config
    dest: datasciencepipelines
    git.url: https://github.com/opendatahub-io/data-science-pipelines-operator
    git.commit: a27bc4b5a1392b125ea7497d6288e62e0c4907f3
  odh-kuberay-operator-controller:
    src: ray-operator/config
    dest: ray
    git.url: https://github.com/opendatahub-io/kuberay
    git.commit: f991c184e326bdfdce4c072604d08ccd1d69a37e
  odh-trustyai-service-operator:
    src: config
    dest: trustyai
    git.url: https://github.com/opendatahub-io/trustyai-service-operator
    git.commit: ce63b1d59f337579939d56c9a1ed205ae3c701f0
  odh-model-controller:
    src: config
    dest: modelcontroller
    git.url: https://github.com/opendatahub-io/odh-model-controller
    git.commit: c0ad4f386ab2d33c213b7b3b81e293c593b7e03f
  odh-model-registry-operator:
    src: config
    dest: modelregistry
    git.url: https://github.com/opendatahub-io/model-registry-operator
    git.commit: cffe9a5805e1a937b1044a47abf5709b52f2db43
  odh-dashboard:
    src: manifests
    dest: dashboard
    git.url: https://github.com/opendatahub-io/odh-dashboard
    git.commit: 8e77c4f52de37f02215a25505a03abfe0febbf93
  odh-training-operator:
    src: manifests
    dest: trainingoperator
    git.url: https://github.com/opendatahub-io/training-operator
    git.commit: da2a67ce5520e44d1ca361b4366d697a0171b9fd
  odh-feast-operator:
    src: infra/feast-operator/config
    dest: feastoperator
    git.url: https://github.com/opendatahub-io/feast
    git.commit: 124117138b5685c0d9aff8fc0855ce522dd10b60
  odh-llama-stack-k8s-operator:
    src: config
    dest: llamastackoperator
    git.url: https://github.com/opendatahub-io/llama-stack-k8s-operator
    git.commit: 5ad598b5d7da67e72ad29ce4717eb360c386a60c
  odh-trainer:
    src: manifests
    dest: trainer
    git.url: https://github.com/opendatahub-io/trainer
    git.commit: 30bdcb8b0900e17e71793a0ef67bb950498dd462
additional_meta:
  odh-trustyai-service:
    git.url: https://github.com/opendatahub-io/trustyai-explainability
    git.commit: 6199ea9b05e1dcf837fdeeb84e59bfca6b8c1eb0
  odh-mlmd-grpc-server:
    git.url: https://github.com/opendatahub-io/ml-metadata
    git.commit: bb983150d1f0a0526e35b8366e03a850f6350b10
  odh-ml-pipelines-api-server-v2:
    git.url: https://github.com/opendatahub-io/data-science-pipelines
    git.commit: d5e0ae8ac806902faab07a8564054020a4c689d2
  odh-ml-pipelines-persistenceagent-v2:
    git.url: https://github.com/opendatahub-io/data-science-pipelines
    git.commit: d5e0ae8ac806902faab07a8564054020a4c689d2
  odh-ml-pipelines-scheduledworkflow-v2:
    git.url: https://github.com/opendatahub-io/data-science-pipelines
    git.commit: d5e0ae8ac806902faab07a8564054020a4c689d2
  odh-ml-pipelines-driver:
    git.url: https://github.com/opendatahub-io/data-science-pipelines
    git.commit: d5e0ae8ac806902faab07a8564054020a4c689d2
  odh-ml-pipelines-launcher:
    git.url: https://github.com/opendatahub-io/data-science-pipelines
    git.commit: d5e0ae8ac806902faab07a8564054020a4c689d2
  odh-data-science-pipelines-argo-argoexec:
    git.url: https://github.com/opendatahub-io/argo-workflows
    git.commit: 47b594a506937c9977f544f9430a5c3ae138c861
  odh-data-science-pipelines-argo-workflowcontroller:
    git.url: https://github.com/opendatahub-io/argo-workflows
    git.commit: 47b594a506937c9977f544f9430a5c3ae138c861
  odh-model-registry:
    git.url: https://github.com/opendatahub-io/model-registry
    git.commit: a8caf754497ce236e1f4976283cd2399d7e26d38
  odh-feature-server:
    git.url: https://github.com/opendatahub-io/feast
    git.commit: 124117138b5685c0d9aff8fc0855ce522dd10b60
  odh-llm-d-inference-scheduler:
    git.url: https://github.com/opendatahub-io/llm-d-inference-scheduler
    git.commit: 134b26ba05276c1d56e72617f46aad37b21936e9
  odh-llm-d-routing-sidecar:
    git.url: https://github.com/opendatahub-io/llm-d-routing-sidecar
    git.commit: ab94456dc48ead90f997a8566e0570b5b4482730
  odh-must-gather:
    git.url: https://github.com/opendatahub-io/must-gather
    git.commit: 9a95c808e7e78156f325552d4a99206fbdb47126
  odh-kserve-agent:
    git.url: https://github.com/opendatahub-io/kserve
    git.commit: 6e7919c9933c42847731ba52b9f3387e097b504d
  odh-kserve-router:
    git.url: https://github.com/opendatahub-io/kserve
    git.commit: 6e7919c9933c42847731ba52b9f3387e097b504d
  odh-kserve-storage-initializer:
    git.url: https://github.com/opendatahub-io/kserve
    git.commit: 6e7919c9933c42847731ba52b9f3387e097b504d
  odh-ta-lmes-driver:
    git.url: https://github.com/opendatahub-io/trustyai-service-operator
    git.commit: b07b6766890d675d8242b601cb5417b7cc3a6aac
  odh-ta-lmes-job:
    git.url: https://github.com/opendatahub-io/lm-evaluation-harness
    git.commit: d6c447a9f21fb7234f281397587690ebef46e664
  odh-fms-guardrails-orchestrator:
    git.url: https://github.com/opendatahub-io/fms-guardrails-orchestrator
    git.commit: 4dfbbbc6a02b7456f254a59890ffe59c22aa2b55
  odh-trustyai-vllm-orchestrator-gateway:
    git.url: https://github.com/opendatahub-io/vllm-orchestrator-gateway
    git.commit: 6494163b9a0b417bfa7964002bd2e0572147d5f5
  odh-built-in-detector:
    git.url: https://github.com/opendatahub-io/guardrails-detectors
    git.commit: 28dcc522f9ed3e1c8c45f4902f8eafee2ecf7b0b
  odh-pipeline-runtime-datascience-cpu-py312:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-pipeline-runtime-minimal-cpu-py312:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-pipeline-runtime-pytorch-cuda-py312:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-pipeline-runtime-pytorch-rocm-py312:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-pipeline-runtime-tensorflow-cuda-py312:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-pipeline-runtime-tensorflow-rocm-py312:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-workbench-codeserver-datascience-cpu-py312:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-workbench-jupyter-datascience-cpu-py312:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-workbench-jupyter-minimal-cpu-py312:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-workbench-jupyter-minimal-cuda-py312:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-workbench-jupyter-minimal-rocm-py312:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: 6e3e9fb8bfe87057ffcc9c332d9175a3ee0c3987
  odh-workbench-jupyter-pytorch-cuda-py312:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-workbench-jupyter-pytorch-rocm-py312:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-workbench-jupyter-tensorflow-cuda-py312:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-workbench-jupyter-tensorflow-rocm-py312:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-workbench-jupyter-trustyai-cpu-py312:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-guardrails-detector-huggingface-runtime:
    git.url: https://github.com/opendatahub-io/guardrails-detectors
    git.commit: 28dcc522f9ed3e1c8c45f4902f8eafee2ecf7b0b
  odh-openvino-model-server:
    git.url: https://github.com/opendatahub-io/openvino_model_server
    git.commit: c2720127ae26a6d82b6751426cad12f2518d9c47
  odh-vllm-cpu:
    git.url: https://github.com/opendatahub-io/vllm-cpu
    git.commit: b15131d439b20c30521f501409d9802b6ca533ce
  odh-vllm-gaudi:
    git.url: https://github.com/opendatahub-io/vllm-gaudi
    git.commit: 3a8e59eade4155d5151b530dd6eb873c1e091e96
  odh-model-registry-job-async-upload:
    git.url: https://github.com/opendatahub-io/model-registry
    git.commit: a8caf754497ce236e1f4976283cd2399d7e26d38
  odh-llama-stack-core:
    git.url: https://gitlab.com/redhat/rhel-ai/llama-stack/containers
    git.commit: 2cbd781ea0404730022d57b3345c4c8d4d0a61af
  odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312:
    git.url: https://github.com/opendatahub-io/notebooks
    git.commit: 724e04c7521ae1364fbafe91b81eaf803277d77f
  odh-model-metadata-collection:
    git.url: https://github.com/opendatahub-io/model-metadata-collection
    git.commit: 2e4c260258c4e23fdc7f9e83e4bc740f5ae8b7be
  odh-mod-arch-gen-ai:
    git.url: https://github.com/opendatahub-io/odh-dashboard
    git.commit: 8e77c4f52de37f02215a25505a03abfe0febbf93
  odh-kube-auth-proxy:
    git.url: https://github.com/opendatahub-io/kube-auth-proxy
    git.commit: 558ba9d2294cb73415bc16baa81254843bc2f091
  odh-maas-api:
    git.url: https://github.com/opendatahub-io/maas-billing
    git.commit: 53ecf9eaa0d24f084ee8b3f91798799a4edab6c0
  odh-model-performance-data:
    git.url: https://github.com/opendatahub-io/models-perf-benchmark-data
    git.commit: 1c6eb95598af6254f523ad830b44a207e35db37c
  odh-trustyai-ragas-lls-provider-dsp:
    git.url: https://github.com/opendatahub-io/llama-stack-provider-ragas
    git.commit: fb6fe77e92e85ce96bf19e0becc53eb0bfc22ea4
  odh-training-cuda121-torch24-py311:
    git.url: https://github.com/opendatahub-io/distributed-workloads
    git.commit: 7e1c2d0117261292d036f014dd09a0e3074ed1fd
  odh-training-cuda124-torch25-py311:
    git.url: https://github.com/opendatahub-io/distributed-workloads
    git.commit: 070ba881a7d5927d5bd6f4cd9650088138a90400
  odh-training-cuda128-torch28-py312:
    git.url: https://github.com/opendatahub-io/distributed-workloads
    git.commit: ea718d1d42cb489eebbba9d7d67da76345cac37d
  odh-training-rocm62-torch24-py311:
    git.url: https://github.com/opendatahub-io/distributed-workloads
    git.commit: 8d62c5933f22005614c9e565ad18df890fa24d12
  odh-training-rocm62-torch25-py311:
    git.url: https://github.com/opendatahub-io/distributed-workloads
    git.commit: 1c6062e5482eb55673524975756cf209d48bbfcb
  odh-training-rocm64-torch28-py312:
    git.url: https://github.com/opendatahub-io/distributed-workloads
    git.commit: 61e655ba9363820d5fab9b568ef7921f55d003a9
  odh-mod-arch-model-registry:
    git.url: https://github.com/opendatahub-io/odh-dashboard
    git.commit: 8e77c4f52de37f02215a25505a03abfe0febbf93
